"""add restaurant external source fields

Revision ID: 5f958c6c5b89
Revises: 7d4a0d712a63
Create Date: 2026-07-31 15:48:09.986743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f958c6c5b89'
down_revision: Union[str, Sequence[str], None] = '7d4a0d712a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('source', sa.String(length=20), nullable=True))
    op.add_column('restaurants', sa.Column('external_id', sa.String(length=50), nullable=True))
    op.create_unique_constraint('uq_restaurants_source_external_id', 'restaurants', ['source', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_restaurants_source_external_id', 'restaurants', type_='unique')
    op.drop_column('restaurants', 'external_id')
    op.drop_column('restaurants', 'source')
    # ### end Alembic commands ###
